version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      IS_PERSISTENT: TRUE
      PERSIST_DIRECTORY: /chroma/chroma
  embedding-service:
    build: ./embedding-service
    container_name: embedding-service
    ports:
      - "8001:8000"

  backend:
    build: ./backend
    depends_on:
      - embedding-service
      - chromadb
volumes:
  chroma_data: