FROM python:3.10-slim

WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]